# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  node: circleci/node@5.0.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
    install:
      docker:
        - image: cimg/base:stable
      steps:
        - checkout
        - node/install-packages:
            pkg-manager: yarn
        - persist_to_workspace:
            root: ~/coveralls-go
            paths:
              - .
    lint:
        docker:
          - image: cimg/base:stable
        steps:
          - attach_workspace:
              at: ~/coveralls-go
          - run:
              name: 'Run eslint'
              command: 'yarn lint'
    prettier:
        docker:
          - image: cimg/base:stable
        steps:
          - attach_workspace:
              at: ~/coveralls-go
          - run:
              name: 'Run prettier'
              command: 'yarn prettier'
    test:
        docker:
          - image: cimg/base:stable
        steps:
          - attach_workspace:
              at: ~/coveralls-go
          - run:
              name: 'Run tests'
              command: 'yarn test'

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
    dev:
      jobs:
        - install
        - lint
        - prettier
        - test
