# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
    node: circleci/node@5.0.2

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
    install:
        executor: node/default
        steps:
            - checkout
            - node/install-packages:
                  pkg-manager: yarn
            - persist_to_workspace:
                  root: .
                  paths:
                      - ./
    lint:
        executor: node/default
        steps:
            - attach_workspace:
                  at: .
            - run:
                  name: 'Run eslint'
                  command: 'yarn lint'
    prettier:
        executor: node/default
        steps:
            - attach_workspace:
                  at: .
            - run:
                  name: 'Run prettier'
                  command: 'yarn prettier'
    test:
        executor: node/default
        steps:
            - attach_workspace:
                  at: .
            - run:
                  name: 'Run tests'
                  command: 'yarn test:ci'
    publish:
        executor: node/default
        steps:
            - attach_workspace:
                  at: .
            - run:
                  name: 'Create production package'
                  command: 'yarn build'
            - run:
                  name: 'Publish to npm'
                  command: |
                      npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
                      npm publish

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
    main:
        jobs:
            - install
            - lint:
                  requires:
                      - install
            - prettier:
                  requires:
                      - lint
            - test:
                  requires:
                      - prettier
            - authorize:
                  type: approval
                  requires:
                      - test
                  filters:
                      branches:
                          only:
                              - /main/
            - publish:
                  requires:
                      - authorize
                  filters:
                      branches:
                          only:
                              - /main/
